apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-tunnels
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflare-tunnels
  template:
    metadata:
      labels:
        app: cloudflare-tunnels
    spec:
      containers:
      - name: minio-tunnel
        image: cloudflare/cloudflared:latest
        args: ["tunnel", "--url", "http://localhost:9001"]
      - name: serving-tunnel
        image: cloudflare/cloudflared:latest
        args: ["tunnel", "--url", "http://localhost:8000"]
      - name: prometheus-tunnel
        image: cloudflare/cloudflared:latest
        args: ["tunnel", "--url", "http://localhost:9090"]
      - name: taxi-api-tunnel
        image: cloudflare/cloudflared:latest
        args: ["tunnel", "--url", "http://localhost:8080"] #taxi-api svc