apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-tunnels
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflare-tunnels
  template:
    metadata:
      labels:
        app: cloudflare-tunnels
    spec:
      containers:
      - name: minio-tunnel
        image: cloudflare/cloudflared:latest
        args: ["tunnel", "--url", "http://minio:9000"] # K8s Service Name:Port
      - name: kafka-tunnel  
        image: cloudflare/cloudflared:latest
        args: ["tunnel", "--url", "http://kafka:9092"] # K8s Service Name:Port
      - name: serving-tunnel
        image: cloudflare/cloudflared:latest
        args: ["tunnel", "--url", "http://taxi-serving-service:80"]
      - name: prometheus-tunnel
        image: cloudflare/cloudflared:latest
        args: ["tunnel", "--url", "http://prometheus:9090"]
      - name: taxi-api-tunnel
        image: cloudflare/cloudflared:latest
        args: ["tunnel", "--url", "http://taxi-api-service:8080"]