# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: taxi-monitoring-data
# spec:
#   accessModes:
#     - ReadWriteOnce #ReadWriteMany #
#   resources:
#     requests:
#       storage: 1Gi