apiVersion: batch/v1
kind: CronJob
metadata:
  name: pipeline-1-ingestion
spec:
  schedule: "0 * * * *"  # Runs every 1 hr
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ingestion-container
            image: myregistry/taxi-pipeline-1:latest
            envFrom:
            - secretRef:
                name: minio-credentials
          restartPolicy: OnFailure