apiVersion: batch/v1
kind: CronJob
metadata:
  name: pipeline-1-ingestion
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ingestion-container
            image: taxi-api 
            command: ["python", "src/producer.py"]
            envFrom:
            - secretRef:
                name: minio-credentials
            env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
          restartPolicy: OnFailure