apiVersion: batch/v1
kind: Job
metadata:
  name: pipeline-2-training
spec:
  template:
    spec:
      containers:
      - name: training-container
        image: taxi-api
        command: ["python", "scripts/train.py"]
        env:
        # Tell MLflow to use MinIO for Artifacts
        - name: MLFLOW_S3_ENDPOINT_URL
          value: "http://minio:9000"
        # Tell MLflow to use Postgres for the Model Registry Metadata
        - name: MLFLOW_TRACKING_URI
          value: "postgresql://airflow:airflow@airflow-postgres:5432/airflow"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: accesskey
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: secretkey
      restartPolicy: Never
  backoffLimit: 1