apiVersion: batch/v1
kind: Job
metadata:
  name: pipeline-2-training
spec:
  template:
    spec:
      initContainers:
      - name: step-1-train
        image: taxi-api
        command: ["python", "src/models/train.py"]
        env:
        - name: MLFLOW_S3_ENDPOINT_URL
          value: "http://minio:9000"
        - name: MLFLOW_TRACKING_URI
          value: "http://mlflow:5000"
        envFrom:
        - secretRef:
            name: minio-credentials

      - name: step-2-tune
        image: taxi-api
        command: ["python", "src/models/tune.py"]
        env:
        - name: MLFLOW_S3_ENDPOINT_URL
          value: "http://minio:9000"
        - name: MLFLOW_TRACKING_URI
          value: "http://mlflow:5000"
        envFrom:
        - secretRef:
            name: minio-credentials

      containers:
      - name: step-3-register
        image: taxi-api
        command: ["python", "src/models/register_best_model.py"]
        env:
        - name: MLFLOW_S3_ENDPOINT_URL
          value: "http://minio:9000"
        - name: MLFLOW_TRACKING_URI
          value: "http://mlflow:5000"
        envFrom:
        - secretRef:
            name: minio-credentials

      restartPolicy: Never
  backoffLimit: 1