apiVersion: batch/v1
kind: Job
metadata:
  name: pipeline-2-training
spec:
  template:
    spec:
      containers:
      - name: training-container
        image: taxi-api
        # This runs INSIDE the Linux container, so 'sh' is perfectly safe.
        command: ["sh", "-c",  "python src/models/train.py && python src/models/tune.py && python src/models/register_best_model.py"]
        env:
        - name: MLFLOW_S3_ENDPOINT_URL
          value: "http://minio:9000"
        - name: MLFLOW_TRACKING_URI
          value: "http://mlflow:5000"
        envFrom:
        - secretRef:
            name: minio-credentials
      restartPolicy: Never
  backoffLimit: 1