apiVersion: v1
kind: Service

metadata:
  name: taxi-api-service

spec:
  selector:
    app: taxi-api

  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

  type: NodePort #ClusterIP #